from startech.generalclass import getVersion
from startech.generalclass import getDate
from startech.generalclass import getDateTime
from startech.generalclass import checkToken
from startech.generalclass import checkRoot
from startech.generalclass import combineLists
from startech.generalclass import alignList
from startech.generalclass import insertList
from startech.generalclass import getTfile
from startech.generalclass import setupFiles
import startech.logclass as log
import startech.settingsclass as settings
