from generalclass import getVersion
from generalclass import getDate
from generalclass import getDateTime
from generalclass import checkToken
from generalclass import checkRoot
from generalclass import combineLists
from generalclass import alignList
from generalclass import insertList
from generalclass import getTfile
import logclass as log
import settingsclass as settings
